### PR TITLE
Added Circle

### PR DESCRIPTION
**Pull request by bullyhunter1917**

### CODE REVIEW

**Review by WiktorOgrodnik — APPROVED** [review]
Seems ok

**Review by Skrollek — CHANGES_REQUESTED** [review]
Formula for calculating vertex points is over-complicated.
Check smaller number of points for example 40.

**Review by WiktorOgrodnik — APPROVED** [review]
Ok, now this is more clear

**Review by Skrollek — APPROVED** [review]
Ok

**Pull request merged**
